name: create-post

on: [release]

jobs:
  make-a-new-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get date
        id: date
        run: echo "NOW=$(date +%Y-%m-%d)" >> $GITHUB_ENV
        
      - name: Create post
        # uses: finnp/create-file-action@1.0.0
        #env:
#          FILE_NAME: "docs/_posts/${{ env.NOW }}-${{ github.run_number }}.md"
#          FILE_CONTENT: "---\nlayout: post\ntitle:  'Release 0.${{ github.run_number }}'\ndate:   ${{ env.NOW }}\ncategories: release\n---\nTest content"
        run:  |
              cat << 'EOF' >> docs/_posts/${{ env.NOW }}-release-${{ github.run_number }}.md
              ---
              layout: post
              title:  'Release 0.${{ github.run_number }}'
              date:   ${{ env.NOW }}
              categories: release
              ---
              Test content
              EOF
      
           
      - name: Commit to Github
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Auto commit new post
          branch: gh-pages
          file_pattern: docs/_posts/*.md
          # push_options: '--force'  
